name: PY Test slider

on:
  push:
#    paths:
#    - '**.py'

jobs:
  test:
    name: Test ${{ matrix.python }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        python:
          - "2.7"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install
        run: |
          pip install wheel
          pip install coverage
          pip install lxml
          pip install zope.testrunner
          pip install webresource
          pip install yafowil
          pip install -e .[test]
      - name: Run tests
        run: |
          python --version
          python -m yafowil.widget.slider.tests
      - name: Run coverage
        run: |
          coverage run --source=src/yafowil/widget/slider --omit=src/yafowil/widget/slider/example.py -m yafowil.widget.slider.tests
          coverage report --fail-under=99
