name: PY Test slider

on:
  push:
    paths:
    - '**.py'

jobs:
  test:
    name: Test ${{ matrix.python }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        python:
          - "2.7"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install
        run: |
          make install
      - name: Run tests
        run: |
          make test
      - name: Run coverage
        run: |
          make coverage
